version: "3.8"

services:
  inventory-service:
    build:
      context: .
      dockerfile: ./inventory_service/Dockerfile
    image: inventory-service:latest
    container_name: inventory-service
    ports:
      - "8000:8000"
    restart: always


  order-service:
    build:
      context: .
      dockerfile: ./order_service/Dockerfile
    image: order-service:latest
    container_name: order-service
    ports:
      - "8001:8001"
    depends_on:
      - inventory-service
    restart: always
    environment:
      - INVENTORY_SERVICE_URL=http://inventory-service:8000